version: '3.7'

services:
  database:
    image: 'mysql:latest'
    container_name: mysql_agenda
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_USER: '${DB_USERNAME}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    restart: always

    networks:
      - agenda_sys_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - agenda_sys_network

  agenda_app:
    depends_on:
      - database
    build: .
    env_file: .env
    environment:
      - DB_HOST=database
    ports:
      - "80:80"
      - "443:443"
    container_name: agenda_app
    tty: true
    networks:
      - agenda_sys_network
    restart: always
    volumes:
      - ./:/var/www/html/agenda_app
networks:
  agenda_sys_network:
    driver: bridge
